/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { post } from '@/api/http'
import type { LoginBody, LoginData, SysUser } from '@/types/entity'

export function login(body: LoginBody): Promise<LoginData> {
  return post<LoginData>('/login', body)
}

export function register(body: SysUser): Promise<void> {
  return post<void>('/register', body)
}
