 
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { AgriCropBatch, AgriFarmland, BaseCropVariety } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListCropFarmlandParams {
  pageNum?: number | string
  pageSize?: number | string
  name?: string
}

export function listCropFarmland(params: ListCropFarmlandParams): Promise<PageResult<AgriFarmland>> {
  return get<PageResult<AgriFarmland>>('/crop/farmland/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, name: params.name } })
}

export function getCropFarmlandAll(): Promise<AgriFarmland[]> {
  return get<AgriFarmland[]>('/crop/farmland/all')
}

export function createCropFarmland(body: AgriFarmland): Promise<void> {
  return post<void>('/crop/farmland', body)
}

export function updateCropFarmland(body: AgriFarmland): Promise<void> {
  return put<void>('/crop/farmland', body)
}

export interface RemoveCropFarmlandByIdsParams {
  ids: number | string
}

export function removeCropFarmlandByIds(params: RemoveCropFarmlandByIdsParams): Promise<void> {
  return del<void>(`/crop/farmland/${params.ids}`)
}

export interface ListCropVarietyParams {
  pageNum?: number | string
  pageSize?: number | string
  cropName?: string
}

export function listCropVariety(params: ListCropVarietyParams): Promise<PageResult<BaseCropVariety>> {
  return get<PageResult<BaseCropVariety>>('/crop/variety/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, cropName: params.cropName } })
}

export function getCropVarietyAll(): Promise<BaseCropVariety[]> {
  return get<BaseCropVariety[]>('/crop/variety/all')
}

export function createCropVariety(body: BaseCropVariety): Promise<void> {
  return post<void>('/crop/variety', body)
}

export function updateCropVariety(body: BaseCropVariety): Promise<void> {
  return put<void>('/crop/variety', body)
}

export interface RemoveCropVarietyByIdsParams {
  ids: number | string
}

export function removeCropVarietyByIds(params: RemoveCropVarietyByIdsParams): Promise<void> {
  return del<void>(`/crop/variety/${params.ids}`)
}

export interface ListCropBatchParams {
  pageNum?: number | string
  pageSize?: number | string
  batchNo?: string | number
  status?: number | string
  farmlandId?: number | string
}

export function listCropBatch(params: ListCropBatchParams): Promise<PageResult<AgriCropBatch>> {
  return get<PageResult<AgriCropBatch>>('/crop/batch/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, batchNo: params.batchNo, status: params.status, farmlandId: params.farmlandId } })
}

export function createCropBatch(body: AgriCropBatch): Promise<void> {
  return post<void>('/crop/batch', body)
}

export function updateCropBatch(body: AgriCropBatch): Promise<void> {
  return put<void>('/crop/batch', body)
}

export interface RemoveCropBatchByIdsParams {
  ids: number | string
}

export function removeCropBatchByIds(params: RemoveCropBatchByIdsParams): Promise<void> {
  return del<void>(`/crop/batch/${params.ids}`)
}

export function startBatch(id: number | string): Promise<void> {
  return put<void>(`/crop/batch/${id}/start`)
}

export function pauseBatch(id: number | string): Promise<void> {
  return put<void>(`/crop/batch/${id}/pause`)
}

export function harvestBatch(id: number | string): Promise<void> {
  return put<void>(`/crop/batch/${id}/harvest`)
}

export function abandonBatch(id: number | string): Promise<void> {
  return put<void>(`/crop/batch/${id}/abandon`)
}

export function archiveBatch(id: number | string): Promise<void> {
  return put<void>(`/crop/batch/${id}/archive`)
}
