/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { BaseCropVariety, CropBatch, GrowthStageLog } from '@/api/types/models'
import type { MpPage } from '@/api/types/http'

export function createCropBatch(body: CropBatch): Promise<void> {
  return post<void>('/crop/batch', body)
}

export function updateCropBatch(body: CropBatch): Promise<void> {
  return put<void>('/crop/batch', body)
}

export interface ListCropBatchParams {
  pageNum?: number | string
  pageSize?: number | string
  plotId?: number | string
  currentStage?: string | number
}

export function listCropBatch(params: ListCropBatchParams): Promise<MpPage<CropBatch>> {
  return get<MpPage<CropBatch>>('/crop/batch/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, plotId: params.plotId, currentStage: params.currentStage } })
}

export interface RemoveCropBatchByIdsParams {
  ids: number | string
}

export function removeCropBatchByIds(params: RemoveCropBatchByIdsParams): Promise<void> {
  return del<void>(`/crop/batch/${params.ids}`)
}

export function createCropGrowthLog(body: GrowthStageLog): Promise<void> {
  return post<void>('/crop/growth-log', body)
}

export interface ListCropGrowthLogParams {
  batchId: number | string
}

export function listCropGrowthLog(params: ListCropGrowthLogParams): Promise<GrowthStageLog[]> {
  return get<GrowthStageLog[]>(`/crop/growth-log/list/${params.batchId}`)
}

export function createCropVariety(body: BaseCropVariety): Promise<void> {
  return post<void>('/crop/variety', body)
}

export function updateCropVariety(body: BaseCropVariety): Promise<void> {
  return put<void>('/crop/variety', body)
}

export function getCropVarietyAll(): Promise<BaseCropVariety[]> {
  return get<BaseCropVariety[]>('/crop/variety/all')
}

export interface ListCropVarietyParams {
  pageNum?: number | string
  pageSize?: number | string
  cropName?: string
}

export function listCropVariety(params: ListCropVarietyParams): Promise<MpPage<BaseCropVariety>> {
  return get<MpPage<BaseCropVariety>>('/crop/variety/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, cropName: params.cropName } })
}

export interface RemoveCropVarietyByIdsParams {
  ids: number | string
}

export function removeCropVarietyByIds(params: RemoveCropVarietyByIdsParams): Promise<void> {
  return del<void>(`/crop/variety/${params.ids}`)
}
