 
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { AgriTaskRule, IotSensorData } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListIotDataParams {
  pageNum?: number | string
  pageSize?: number | string
  plotId?: number | string
  sensorType?: string | number
}

export function listIotData(params: ListIotDataParams): Promise<PageResult<IotSensorData>> {
  return get<PageResult<IotSensorData>>('/iot/data/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, plotId: params.plotId, sensorType: params.sensorType } })
}

export interface ListIotRuleParams {
  pageNum?: number | string
  pageSize?: number | string
}

export function listIotRule(params: ListIotRuleParams): Promise<PageResult<AgriTaskRule>> {
  return get<PageResult<AgriTaskRule>>('/iot/rule/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize } })
}

export function createIotRule(body: AgriTaskRule): Promise<void> {
  return post<void>('/iot/rule', body)
}

export function updateIotRule(body: AgriTaskRule): Promise<void> {
  return put<void>('/iot/rule', body)
}

export function removeIotRuleById(id: number | string): Promise<void> {
  return del<void>(`/iot/rule/${id}`)
}
