/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { MaterialInfo, MaterialStockLog } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListMaterialInfoParams {
  pageNum?: number | string
  pageSize?: number | string
  name?: string
  category?: string | number
}

export function listMaterialInfo(params: ListMaterialInfoParams): Promise<PageResult<MaterialInfo>> {
  return get<PageResult<MaterialInfo>>('/material/info/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, name: params.name, category: params.category } })
}

export function getMaterialInfoLowStock(): Promise<MaterialInfo[]> {
  return get<MaterialInfo[]>('/material/info/low-stock')
}

export function getMaterialInfoAll(): Promise<MaterialInfo[]> {
  return get<MaterialInfo[]>('/material/info/all')
}

export function createMaterialInfo(body: MaterialInfo): Promise<void> {
  return post<void>('/material/info', body)
}

export function updateMaterialInfo(body: MaterialInfo): Promise<void> {
  return put<void>('/material/info', body)
}

export interface RemoveMaterialInfoByIdsParams {
  ids: number | string
}

export function removeMaterialInfoByIds(params: RemoveMaterialInfoByIdsParams): Promise<void> {
  return del<void>(`/material/info/${params.ids}`)
}

export interface ListMaterialStockLogParams {
  pageNum?: number | string
  pageSize?: number | string
  materialId?: number | string
  changeType?: string | number
}

export function listMaterialStockLog(params: ListMaterialStockLogParams): Promise<PageResult<MaterialStockLog>> {
  return get<PageResult<MaterialStockLog>>('/material/stock-log/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, materialId: params.materialId, changeType: params.changeType } })
}
