/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { MaterialInfo, MaterialInoutLog } from '@/types/entity'
import type { MpPage } from '@/types/api'

export function createMaterialInfo(body: MaterialInfo): Promise<void> {
  return post<void>('/material/info', body)
}

export function updateMaterialInfo(body: MaterialInfo): Promise<void> {
  return put<void>('/material/info', body)
}

export interface ListMaterialInfoParams {
  pageNum?: number | string
  pageSize?: number | string
  name?: string
  category?: string | number
}

export function listMaterialInfo(params: ListMaterialInfoParams): Promise<MpPage<MaterialInfo>> {
  return get<MpPage<MaterialInfo>>('/material/info/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, name: params.name, category: params.category } })
}

export interface RemoveMaterialInfoByIdsParams {
  ids: number | string
}

export function removeMaterialInfoByIds(params: RemoveMaterialInfoByIdsParams): Promise<void> {
  return del<void>(`/material/info/${params.ids}`)
}

export function createMaterialLogExecute(body: MaterialInoutLog): Promise<void> {
  return post<void>('/material/log/execute', body)
}

export interface ListMaterialLogParams {
  pageNum?: number | string
  pageSize?: number | string
  materialId?: number | string
}

export function listMaterialLog(params: ListMaterialLogParams): Promise<MpPage<MaterialInoutLog>> {
  return get<MpPage<MaterialInoutLog>>('/material/log/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, materialId: params.materialId } })
}
