/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { PaymentRecord, PurchaseOrder, PurchaseOrderItem } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListPurchaseParams {
  pageNum?: number | string
  pageSize?: number | string
  status?: number | string
  supplierId?: number | string
}

export function listPurchase(params: ListPurchaseParams): Promise<PageResult<PurchaseOrder>> {
  return get<PageResult<PurchaseOrder>>('/purchase/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, status: params.status, supplierId: params.supplierId } })
}

export function createPurchase(body: PurchaseOrder): Promise<void> {
  return post<void>('/purchase', body)
}

export function updatePurchase(body: PurchaseOrder): Promise<void> {
  return put<void>('/purchase', body)
}

export interface RemovePurchaseByIdsParams {
  ids: number | string
}

export function removePurchaseByIds(params: RemovePurchaseByIdsParams): Promise<void> {
  return del<void>(`/purchase/${params.ids}`)
}

export function confirmPurchase(id: number | string): Promise<void> {
  return put<void>(`/purchase/${id}/confirm`)
}

export function cancelPurchase(id: number | string): Promise<void> {
  return put<void>(`/purchase/${id}/cancel`)
}

export function getPurchaseItemsByOrderId(orderId: number | string): Promise<PurchaseOrderItem[]> {
  return get<PurchaseOrderItem[]>(`/purchase/${orderId}/items`)
}

export function createPurchaseItems(orderId: number | string, body: PurchaseOrderItem): Promise<void> {
  return post<void>(`/purchase/${orderId}/items`, body)
}

export function updatePurchaseItems(orderId: number | string, body: Array<PurchaseOrderItem>): Promise<void> {
  return put<void>(`/purchase/${orderId}/items`, body)
}

export function getPurchasePaymentsByOrderId(orderId: number | string): Promise<PaymentRecord[]> {
  return get<PaymentRecord[]>(`/purchase/${orderId}/payments`)
}

export function createPurchasePayment(orderId: number | string, body: PaymentRecord): Promise<void> {
  return post<void>(`/purchase/${orderId}/payment`, body)
}

export function receivePurchase(orderId: number | string): Promise<void> {
  return post<void>(`/purchase/${orderId}/receive`)
}

export function updatePurchasePay(id: number | string, body: PurchaseOrder): Promise<void> {
  return put<void>(`/purchase/${id}/pay`, body)
}
