/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { get } from '@/api/http'
import type { DashboardData, DashboardV2Data } from '@/types/entity'

export function getReportDashboard(): Promise<DashboardData> {
  return get<DashboardData>('/report/dashboard')
}

export function getReportDashboardV2(): Promise<DashboardV2Data> {
  return get<DashboardV2Data>('/report/dashboard/v2')
}
