/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { get } from '@/api/http'
import type { CostAnalyticsData, DashboardData, DashboardV2Data, ProductionAnalyticsData, ReportAnalyticsOverviewData, TaskAnalyticsData } from '@/types/entity'

export function getReportDashboard(): Promise<DashboardData> {
  return get<DashboardData>('/report/dashboard')
}

export function getReportDashboardV2(): Promise<DashboardV2Data> {
  return get<DashboardV2Data>('/report/dashboard/v2')
}

export interface GetReportAnalyticsOverviewParams {
  startDate?: string | number
  endDate?: string | number
  granularity?: string | number
  farmlandId?: number | string
  varietyId?: number | string
  assigneeId?: number | string
  materialCategory?: string | number
  supplierId?: number | string
}

export function getReportAnalyticsOverview(params: GetReportAnalyticsOverviewParams): Promise<ReportAnalyticsOverviewData> {
  return get<ReportAnalyticsOverviewData>('/report/analytics/overview', { params: { startDate: params.startDate, endDate: params.endDate, granularity: params.granularity, farmlandId: params.farmlandId, varietyId: params.varietyId, assigneeId: params.assigneeId, materialCategory: params.materialCategory, supplierId: params.supplierId } })
}

export interface GetReportAnalyticsTaskParams {
  startDate?: string | number
  endDate?: string | number
  granularity?: string | number
  farmlandId?: number | string
  varietyId?: number | string
  assigneeId?: number | string
}

export function getReportAnalyticsTask(params: GetReportAnalyticsTaskParams): Promise<TaskAnalyticsData> {
  return get<TaskAnalyticsData>('/report/analytics/task', { params: { startDate: params.startDate, endDate: params.endDate, granularity: params.granularity, farmlandId: params.farmlandId, varietyId: params.varietyId, assigneeId: params.assigneeId } })
}

export interface GetReportAnalyticsProductionParams {
  startDate?: string | number
  endDate?: string | number
  granularity?: string | number
  farmlandId?: number | string
  varietyId?: number | string
}

export function getReportAnalyticsProduction(params: GetReportAnalyticsProductionParams): Promise<ProductionAnalyticsData> {
  return get<ProductionAnalyticsData>('/report/analytics/production', { params: { startDate: params.startDate, endDate: params.endDate, granularity: params.granularity, farmlandId: params.farmlandId, varietyId: params.varietyId } })
}

export interface GetReportAnalyticsCostParams {
  startDate?: string | number
  endDate?: string | number
  granularity?: string | number
  materialCategory?: string | number
  supplierId?: number | string
}

export function getReportAnalyticsCost(params: GetReportAnalyticsCostParams): Promise<CostAnalyticsData> {
  return get<CostAnalyticsData>('/report/analytics/cost', { params: { startDate: params.startDate, endDate: params.endDate, granularity: params.granularity, materialCategory: params.materialCategory, supplierId: params.supplierId } })
}
