/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { SupplierInfo } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListSupplierParams {
  pageNum?: number | string
  pageSize?: number | string
  name?: string
}

export function listSupplier(params: ListSupplierParams): Promise<PageResult<SupplierInfo>> {
  return get<PageResult<SupplierInfo>>('/supplier/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, name: params.name } })
}

export function getSupplierAll(): Promise<SupplierInfo[]> {
  return get<SupplierInfo[]>('/supplier/all')
}

export function createSupplier(body: SupplierInfo): Promise<void> {
  return post<void>('/supplier', body)
}

export function updateSupplier(body: SupplierInfo): Promise<void> {
  return put<void>('/supplier', body)
}

export interface RemoveSupplierByIdsParams {
  ids: number | string
}

export function removeSupplierByIds(params: RemoveSupplierByIdsParams): Promise<void> {
  return del<void>(`/supplier/${params.ids}`)
}
