/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { SysMenu, SysRole, SysUser } from '@/types/entity'
import type { MpPage } from '@/types/api'

export function createSystemMenu(body: SysMenu): Promise<void> {
  return post<void>('/system/menu', body)
}

export function updateSystemMenu(body: SysMenu): Promise<void> {
  return put<void>('/system/menu', body)
}

export function listSystemMenu(): Promise<SysMenu[]> {
  return get<SysMenu[]>('/system/menu/list')
}

export interface RemoveSystemMenuByMenuIdParams {
  menuId: number | string
}

export function removeSystemMenuByMenuId(params: RemoveSystemMenuByMenuIdParams): Promise<void> {
  return del<void>(`/system/menu/${params.menuId}`)
}

export function createSystemRole(body: SysRole): Promise<void> {
  return post<void>('/system/role', body)
}

export function updateSystemRole(body: SysRole): Promise<void> {
  return put<void>('/system/role', body)
}

export interface ListSystemRoleParams {
  pageNum?: number | string
  pageSize?: number | string
  roleName?: string
}

export function listSystemRole(params: ListSystemRoleParams): Promise<MpPage<SysRole>> {
  return get<MpPage<SysRole>>('/system/role/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, roleName: params.roleName } })
}

export interface RemoveSystemRoleByRoleIdsParams {
  roleIds: number | string
}

export function removeSystemRoleByRoleIds(params: RemoveSystemRoleByRoleIdsParams): Promise<void> {
  return del<void>(`/system/role/${params.roleIds}`)
}

export function createSystemUser(body: SysUser): Promise<void> {
  return post<void>('/system/user', body)
}

export function updateSystemUser(body: SysUser): Promise<void> {
  return put<void>('/system/user', body)
}

export interface ListSystemUserParams {
  pageNum?: number | string
  pageSize?: number | string
  username?: string
  realName?: string
  status?: number | string
}

export function listSystemUser(params: ListSystemUserParams): Promise<MpPage<SysUser>> {
  return get<MpPage<SysUser>>('/system/user/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, username: params.username, realName: params.realName, status: params.status } })
}

export interface RemoveSystemUserByUserIdsParams {
  userIds: number | string
}

export function removeSystemUserByUserIds(params: RemoveSystemUserByUserIdsParams): Promise<void> {
  return del<void>(`/system/user/${params.userIds}`)
}

export interface GetSystemUserByUserIdParams {
  userId: number | string
}

export function getSystemUserByUserId(params: GetSystemUserByUserIdParams): Promise<SysUser> {
  return get<SysUser>(`/system/user/${params.userId}`)
}

// ==================== 角色分配 ====================

export function getUserRoles(userId: number): Promise<number[]> {
  return get<number[]>(`/system/user/${userId}/roles`)
}

export function assignUserRoles(userId: number, roleIds: number[]): Promise<void> {
  return put<void>(`/system/user/${userId}/roles`, roleIds)
}

export function listAllRoles(): Promise<SysRole[]> {
  return get<SysRole[]>('/system/role/all')
}
