/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { PasswordChangeRequest, SysMenu, SysRole, SysUser } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListSystemUserParams {
  pageNum?: number | string
  pageSize?: number | string
  username?: string
  realName?: string
  status?: number | string
}

export function listSystemUser(params: ListSystemUserParams): Promise<PageResult<SysUser>> {
  return get<PageResult<SysUser>>('/system/user/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, username: params.username, realName: params.realName, status: params.status } })
}

export function getSystemUserByUserId(userId: number | string): Promise<SysUser> {
  return get<SysUser>(`/system/user/${userId}`)
}

export function createSystemUser(body: SysUser): Promise<void> {
  return post<void>('/system/user', body)
}

export function updateSystemUser(body: SysUser): Promise<void> {
  return put<void>('/system/user', body)
}

export interface RemoveSystemUserByUserIdsParams {
  userIds: number | string
}

export function removeSystemUserByUserIds(params: RemoveSystemUserByUserIdsParams): Promise<void> {
  return del<void>(`/system/user/${params.userIds}`)
}

export function getSystemUserRolesByUserId(userId: number | string): Promise<SysRole[]> {
  return get<SysRole[]>(`/system/user/${userId}/roles`)
}

export function updateSystemUserRoles(userId: number | string): Promise<void> {
  return put<void>(`/system/user/${userId}/roles`)
}

export function updateSystemUserProfile(body: SysUser): Promise<SysUser> {
  return put<SysUser>('/system/user/profile', body)
}

export function updateSystemUserPassword(body: PasswordChangeRequest): Promise<void> {
  return put<void>('/system/user/password', body)
}

export interface ListSystemRoleParams {
  pageNum?: number | string
  pageSize?: number | string
  roleName?: string
}

export function listSystemRole(params: ListSystemRoleParams): Promise<PageResult<SysRole>> {
  return get<PageResult<SysRole>>('/system/role/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, roleName: params.roleName } })
}

export function getSystemRoleAll(): Promise<SysRole[]> {
  return get<SysRole[]>('/system/role/all')
}

export function createSystemRole(body: SysRole): Promise<void> {
  return post<void>('/system/role', body)
}

export function updateSystemRole(body: SysRole): Promise<void> {
  return put<void>('/system/role', body)
}

export interface RemoveSystemRoleByRoleIdsParams {
  roleIds: number | string
}

export function removeSystemRoleByRoleIds(params: RemoveSystemRoleByRoleIdsParams): Promise<void> {
  return del<void>(`/system/role/${params.roleIds}`)
}

export function listSystemMenu(): Promise<SysMenu[]> {
  return get<SysMenu[]>('/system/menu/list')
}

export function createSystemMenu(body: SysMenu): Promise<void> {
  return post<void>('/system/menu', body)
}

export function updateSystemMenu(body: SysMenu): Promise<void> {
  return put<void>('/system/menu', body)
}

export function removeSystemMenuByMenuId(menuId: number | string): Promise<void> {
  return del<void>(`/system/menu/${menuId}`)
}
