/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { AgriTask, TaskAssignRequest, TaskExecutionLog, TaskAcceptDTO, TaskRejectDTO } from '@/api/types/models'
import type { MpPage } from '@/api/types/http'

export function createTask(body: AgriTask): Promise<void> {
  return post<void>('/task', body)
}

export function updateTask(body: AgriTask): Promise<void> {
  return put<void>('/task', body)
}

export function assignTask(body: TaskAssignRequest): Promise<void> {
  return put<void>('/task/assign', body)
}

export function updateTaskAssign(body: TaskAssignRequest): Promise<void> {
  return assignTask(body)
}

export function acceptTask(body: TaskAcceptDTO): Promise<void> {
  return post<void>('/task/accept', body)
}

export function rejectTask(body: TaskRejectDTO): Promise<void> {
  return post<void>('/task/reject', body)
}

export interface ListTaskParams {
  pageNum?: number | string
  pageSize?: number | string
  taskName?: string
  status?: number | string
  executorId?: number | string
}

export function listTask(params: ListTaskParams): Promise<MpPage<AgriTask>> {
  return get<MpPage<AgriTask>>('/task/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskName: params.taskName, status: params.status, executorId: params.executorId } })
}

export function createTaskLog(body: TaskExecutionLog): Promise<void> {
  return post<void>('/task/log', body)
}

export interface ListTaskLogParams {
  pageNum?: number | string
  pageSize?: number | string
  taskId?: number | string
}

export function listTaskLog(params: ListTaskLogParams): Promise<MpPage<TaskExecutionLog>> {
  return get<MpPage<TaskExecutionLog>>('/task/log/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskId: params.taskId } })
}

export interface RemoveTaskByIdsParams {
  ids: number | string
}

export function removeTaskByIds(params: RemoveTaskByIdsParams): Promise<void> {
  return del<void>(`/task/${params.ids}`)
}
