/* eslint-disable */
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { AgriTask, AgriTaskLog, AgriTaskMaterial, TaskAssignRequest, TaskRejectDTO, TaskReviewRequest } from '@/types/entity'
import type { PageResult } from '@/types/api'

export interface ListTaskParams {
  pageNum?: number | string
  pageSize?: number | string
  taskName?: string
  statusV2?: string | number
  assigneeId?: number | string
}

export function listTask(params: ListTaskParams): Promise<PageResult<AgriTask>> {
  return get<PageResult<AgriTask>>('/task/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskName: params.taskName, statusV2: params.statusV2, assigneeId: params.assigneeId } })
}

export function createTask(body: AgriTask): Promise<void> {
  return post<void>('/task', body)
}

export function updateTask(body: AgriTask): Promise<void> {
  return put<void>('/task', body)
}

export function assignTask(body: TaskAssignRequest): Promise<void> {
  return put<void>('/task/assign', body)
}

export function acceptTask(id: number | string): Promise<void> {
  return put<void>(`/task/${id}/accept`)
}

export function rejectTask(id: number | string, body: TaskRejectDTO): Promise<void> {
  return put<void>(`/task/${id}/reject`, body)
}

export interface RemoveTaskByIdsParams {
  ids: number | string
}

export function removeTaskByIds(params: RemoveTaskByIdsParams): Promise<void> {
  return del<void>(`/task/${params.ids}`)
}

export function completeTask(id: number | string): Promise<void> {
  return put<void>(`/task/${id}/complete`)
}

export function reviewTask(id: number | string, body: TaskReviewRequest): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/review`, body)
}

export function suspendTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/suspend`)
}

export function resumeTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/resume`)
}

export function cancelTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/cancel`)
}

export function reassignTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/reassign`)
}

export function getTaskLogByTaskId(taskId: number | string): Promise<AgriTaskLog[]> {
  return get<AgriTaskLog[]>(`/task/log/${taskId}`)
}

export function getTaskMaterialsByTaskId(taskId: number | string): Promise<AgriTaskMaterial[]> {
  return get<AgriTaskMaterial[]>(`/task/${taskId}/materials`)
}

export function createTaskMaterials(taskId: number | string, body: AgriTaskMaterial[]): Promise<void> {
  return post<void>(`/task/${taskId}/materials`, body)
}

export function updateTaskMaterial(id: number | string, body: AgriTaskMaterial): Promise<void> {
  return put<void>(`/task/material/${id}`, body)
}

export interface ListTaskLogParams {
  pageNum?: number | string
  pageSize?: number | string
  taskId?: number | string
  batchId?: number | string
  action?: string | number
}

export function listTaskLog(params: ListTaskLogParams): Promise<PageResult<AgriTaskLog>> {
  return get<PageResult<AgriTaskLog>>('/task/log/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskId: params.taskId, batchId: params.batchId, action: params.action } })
}

export function createTaskLog(body: AgriTaskLog): Promise<void> {
  return post<void>('/task/log', body)
}
