 
// Auto-generated by scripts/generate-api-modules.mjs from openapi/endpoints.json.
// Do not edit this file manually.

import { del, get, post, put } from '@/api/http'
import type { AgriTask, AgriTaskLog, AgriTaskMaterial, TaskAcceptDTO, TaskAssignRequest, TaskRejectDTO } from '@/types/entity'
import type { MpPage } from '@/types/api'

export interface ListTaskParams {
  pageNum?: number | string
  pageSize?: number | string
  taskName?: string
  statusV2?: string | number
  assigneeId?: number | string
}

export function listTask(params: ListTaskParams): Promise<MpPage<AgriTask>> {
  return get<MpPage<AgriTask>>('/task/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskName: params.taskName, statusV2: params.statusV2, assigneeId: params.assigneeId } })
}

export function createTask(body: AgriTask): Promise<void> {
  return post<void>('/task', body)
}

export function updateTask(body: AgriTask): Promise<void> {
  return put<void>('/task', body)
}

export function assignTask(body: TaskAssignRequest): Promise<void> {
  return put<void>('/task/assign', body)
}

export function acceptTask(body: TaskAcceptDTO): Promise<void> {
  return post<void>('/task/accept', body)
}

export function rejectTask(body: TaskRejectDTO): Promise<void> {
  return post<void>('/task/reject', body)
}

export interface RemoveTaskByIdsParams {
  ids: number | string
}

export function removeTaskByIds(params: RemoveTaskByIdsParams): Promise<void> {
  return del<void>(`/task/${params.ids}`)
}

export function completeTask(id: number | string): Promise<void> {
  return post<void>(`/task/${id}/complete`)
}

export function reviewTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/review`)
}

export function suspendTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/suspend`)
}

export function resumeTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/resume`)
}

export function cancelTask(id: number | string): Promise<AgriTask> {
  return del<AgriTask>(`/task/${id}/cancel`)
}

export function reassignTask(id: number | string): Promise<AgriTask> {
  return put<AgriTask>(`/task/${id}/reassign`)
}

export function getTaskLogByTaskId(taskId: number | string): Promise<AgriTaskLog[]> {
  return get<AgriTaskLog[]>(`/task/log/${taskId}`)
}

export function getTaskMaterialsByTaskId(taskId: number | string): Promise<AgriTaskMaterial[]> {
  return get<AgriTaskMaterial[]>(`/task/${taskId}/materials`)
}

export function createTaskMaterials(taskId: number | string, body: AgriTaskMaterial): Promise<void> {
  return post<void>(`/task/${taskId}/materials`, body)
}

export function updateTaskMaterial(id: number | string, body: AgriTaskMaterial): Promise<void> {
  return put<void>(`/task/material/${id}`, body)
}

export interface ListTaskLogParams {
  pageNum?: number | string
  pageSize?: number | string
  taskId?: number | string
  batchId?: number | string
  action?: string | number
}

export function listTaskLog(params: ListTaskLogParams): Promise<MpPage<AgriTaskLog>> {
  return get<MpPage<AgriTaskLog>>('/task/log/list', { params: { pageNum: params.pageNum, pageSize: params.pageSize, taskId: params.taskId, batchId: params.batchId, action: params.action } })
}

export function createTaskLogAdd(body: AgriTaskLog): Promise<void> {
  return post<void>('/task/log/add', body)
}
