export type AppRole = 'ADMIN' | 'FARM_OWNER' | 'TECHNICIAN' | 'WORKER' | 'DEMO'

export const ROLE_ADMIN: AppRole = 'ADMIN'
export const ROLE_FARM_OWNER: AppRole = 'FARM_OWNER'
export const ROLE_TECHNICIAN: AppRole = 'TECHNICIAN'
export const ROLE_WORKER: AppRole = 'WORKER'
export const ROLE_DEMO: AppRole = 'DEMO'

export const ALL_ROLES: AppRole[] = [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_TECHNICIAN, ROLE_WORKER, ROLE_DEMO]

export const MANAGER_ROLES: AppRole[] = [ROLE_ADMIN, ROLE_FARM_OWNER]

export const ROLE_ALIAS_MAP: Record<string, AppRole> = {
  ADMIN: ROLE_ADMIN,
  ROLE_ADMIN: ROLE_ADMIN,
  SUPER_ADMIN: ROLE_ADMIN,
  ROOT: ROLE_ADMIN,
  SYSTEM_ADMIN: ROLE_ADMIN,
  管理员: ROLE_ADMIN,
  超级管理员: ROLE_ADMIN,

  FARM_OWNER: ROLE_FARM_OWNER,
  ROLE_FARM_OWNER: ROLE_FARM_OWNER,
  FARMOWNER: ROLE_FARM_OWNER,
  OWNER: ROLE_FARM_OWNER,
  农场主: ROLE_FARM_OWNER,

  TECHNICIAN: ROLE_TECHNICIAN,
  ROLE_TECHNICIAN: ROLE_TECHNICIAN,
  TECH: ROLE_TECHNICIAN,
  FARMER: ROLE_TECHNICIAN,
  ROLE_FARMER: ROLE_TECHNICIAN,
  技术员: ROLE_TECHNICIAN,
  农户: ROLE_TECHNICIAN,

  WORKER: ROLE_WORKER,
  ROLE_WORKER: ROLE_WORKER,
  STAFF: ROLE_WORKER,
  OPERATOR: ROLE_WORKER,
  工人: ROLE_WORKER,

  DEMO: ROLE_DEMO,
  ROLE_DEMO: ROLE_DEMO,
  演示账号: ROLE_DEMO,
}

export const MENU_ACCESS = {
  dashboard: MANAGER_ROLES,
  system: MANAGER_ROLES,
  taskManage: [...MANAGER_ROLES, ROLE_TECHNICIAN] as AppRole[],
  myTask: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_TECHNICIAN, ROLE_WORKER] as AppRole[],
  taskLog: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_TECHNICIAN, ROLE_WORKER] as AppRole[],
  crop: [...MANAGER_ROLES, ROLE_TECHNICIAN] as AppRole[],
  farmland: [...MANAGER_ROLES, ROLE_TECHNICIAN] as AppRole[],
  materialInventory: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_TECHNICIAN, ROLE_WORKER] as AppRole[],
  materialLog: MANAGER_ROLES,
  supplier: MANAGER_ROLES,
  purchase: MANAGER_ROLES,
  iotMonitor: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_TECHNICIAN] as AppRole[],
  iotRule: MANAGER_ROLES,
  report: MANAGER_ROLES,
}
