export type AppRole = 'ADMIN' | 'FARM_OWNER' | 'MANAGER' | 'FARMER' | 'WORKER' | 'DEMO'

export const ROLE_ADMIN: AppRole = 'ADMIN'
export const ROLE_FARM_OWNER: AppRole = 'FARM_OWNER'
export const ROLE_MANAGER: AppRole = 'MANAGER'
export const ROLE_FARMER: AppRole = 'FARMER'
export const ROLE_WORKER: AppRole = 'WORKER'
export const ROLE_DEMO: AppRole = 'DEMO'

export const ALL_ROLES: AppRole[] = [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_MANAGER, ROLE_FARMER, ROLE_WORKER, ROLE_DEMO]

export const MANAGER_ROLES: AppRole[] = [ROLE_ADMIN, ROLE_FARM_OWNER]

export const ROLE_ALIAS_MAP: Record<string, AppRole> = {
  ADMIN: ROLE_ADMIN,
  ROLE_ADMIN: ROLE_ADMIN,
  SUPER_ADMIN: ROLE_ADMIN,
  ROLE_SUPER_ADMIN: ROLE_ADMIN,
  ROOT: ROLE_ADMIN,
  SYSTEM_ADMIN: ROLE_ADMIN,
  管理员: ROLE_ADMIN,
  超级管理员: ROLE_ADMIN,

  FARM_OWNER: ROLE_FARM_OWNER,
  ROLE_FARM_OWNER: ROLE_FARM_OWNER,
  FARMOWNER: ROLE_FARM_OWNER,
  OWNER: ROLE_FARM_OWNER,
  FARM_ADMIN: ROLE_FARM_OWNER,
  FARMOWNER_ADMIN: ROLE_FARM_OWNER,
  农场主: ROLE_FARM_OWNER,

  MANAGER: ROLE_MANAGER,
  ROLE_MANAGER: ROLE_MANAGER,
  经理: ROLE_MANAGER,

  FARMER: ROLE_FARMER,
  ROLE_FARMER: ROLE_FARMER,
  FARM: ROLE_FARMER,
  GROWER: ROLE_FARMER,
  农户: ROLE_FARMER,
  种植户: ROLE_FARMER,

  WORKER: ROLE_WORKER,
  ROLE_WORKER: ROLE_WORKER,
  STAFF: ROLE_WORKER,
  OPERATOR: ROLE_WORKER,
  工人: ROLE_WORKER,

  DEMO: ROLE_DEMO,
  ROLE_DEMO: ROLE_DEMO,
  演示账号: ROLE_DEMO,
}

export const MENU_ACCESS = {
  dashboard: MANAGER_ROLES,
  system: MANAGER_ROLES,
  taskManage: MANAGER_ROLES,
  myTask: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_MANAGER, ROLE_FARMER, ROLE_WORKER] as AppRole[],
  taskLog: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_MANAGER, ROLE_FARMER, ROLE_WORKER] as AppRole[],
  crop: MANAGER_ROLES,
  materialInventory: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_MANAGER, ROLE_FARMER, ROLE_WORKER] as AppRole[],
  materialLog: MANAGER_ROLES,
  iotMonitor: [ROLE_ADMIN, ROLE_FARM_OWNER, ROLE_FARMER] as AppRole[],
  iotRule: MANAGER_ROLES,
  report: MANAGER_ROLES,
}
